version: '3'
services:
  web:
    build: ./docker
    ports:
      - "8379:80"
    volumes:
      - ".:/var/www/html/"
    environment:
      - APP_ENV=development

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
